### ISSUE TITLE
word2vec endpoint routing

### ISSUE THREAD

**Issue by ankur-gos** [UW-COSMOS/cosmos-visualizer#51]
Currently, there is an issue with the pushed docker image (uwcosmos/visualizer_kb:latest) with regards to the /word2vec/word2vec endpoint. With a backend API route setup, it still routes to the homepage, and never makes a request to the backend.

I suspect this is an nginx routing issue, and Ian suspects some changes between prod and the pushed images.

**Comment by iross** [comment]
Definitely a routing issue. I think this goes away when #51 is fixed, since
it's the lack of an nginx location defined that's causing the issue. Hacky
solution in the meantime if it's holding you up would be to add a similar
rule to `/etc/nginx/nginx.conf` in the running instance of
uwcosmos/visualizer_kb. Don't remember exactly what path it's trying to
hit, but the nginx rule would be something like:

```
events {
  worker_connections  4096;  ## Default: 1024
}

http {
  root /frontend;
  include /etc/nginx/mime.types;
  add_header 'Access-Control-Allow-Origin' '*';

  ##
  # Logging Settings
  ##
  access_log /dev/stdout;
  error_log /dev/stderr;

  server {

    location /api/v1/ {
      proxy_pass http://cosmos_birdnest_backend:5010/api/v1/;
      proxy_http_version 1.1;
      proxy_set_header Update $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
      proxy_connect_timeout       300;
      proxy_send_timeout          300;
      proxy_read_timeout          300;
      send_timeout                300;
    }

    location /word2vec-api/ {
      proxy_pass http://cosmos_birdnest_backend:5010/word2vec/;
      proxy_http_version 1.1;
      proxy_set_header Update $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
      proxy_connect_timeout       300;
      proxy_send_timeout          300;
      proxy_read_timeout          300;
      send_timeout                300;
    }
    client_max_body_size 20M;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
```
I *think* you can modify the nginx.conf and then issue a `nginx -s reload`
within the running image, but not 100% sure on that.

re: the reported difference in prod. The issue there is that the routing to
the APIs isn't done where I expected. On that host, there's a
`server-config` that routes cosmos.wisc.edu/sets/covid into the frontend or
out to the API. It still needs to be cleaned up, but it was made worse by
looking in the wrong place.
